#server:
##访问时路径时必须加的名称
##  context-path: /web
#  port: 8088
#  servlet:
#    context-path: /docking

spring:
  profiles: test
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      #url: jdbc:oracle:thin:@10.10.2.16:1521:ORCL
      #username: ajyhpc
      #password: ajyhpcs
#      url: jdbc:oracle:thin:@localhost:1521:ORCL
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: scott
      password: Smile520
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.center.omd.service.*


      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true

  mvc:
    view:
    # 后台JSP地址前缀
      prefix: /WEB-INF/jsp/
      # 后台JSP地址后缀
      suffix: .jsp
  #配置Redis数据源,开启缓存配置
  cache:
    type: redis
#  #配置Redis数据源,注意配置文件的层级关系
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    # 有密码填密码，没有密码不填
#    password: 123456
#    # 连接超时时间（ms)
#    timeout: 100000
#    # 高版本springboot中使用jedis或者lettuce
#    jedis:
#      pool:
#        # 连接池最大连接数（负值表示无限制）
#        max-active: 8
#        # 连接池最大阻塞等待时间（负值无限制)
#        max-wait: 5000
#        # 最大空闲链接数
#        max-idle: 8
#        # 最小空闲链接数
#        min-idle: 1
    #配置异常拦截
    #  mvc:
    #    throw-exception-if-no-handler-found: true
    #  resources:
    #      add-mappings: false

